# Generated by Django 4.0.2 on 2022-02-22 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(error_messages={'required': 'this is not a valid egyptian number'}, max_length=11, null=True, validators=[users.models.validate_egyptian_number])),
                ('profile_picture', models.ImageField(null=True, upload_to=users.models.image_upload)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('facebook_profile', models.URLField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('state', models.CharField(choices=[('canceld by doctor', 'canceld by doctor'), ('canceld', 'canceld'), ('in processing', 'in processing'), ('missed', 'missed'), ('finished', 'finished')], max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Appiontment_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
